### ISSUE TITLE
Event does not bubble if elements are nested

### ISSUE THREAD

**Issue by XionDelta** [SirLamer/click-confirm#2]
I have found that when use a button with a font awesome icon in it, clicking on confirm does not work.

Looking at the code, i appears that when you click confirm, it will dispatch an event on the target, but this will not bubble, which means that the click handler in the parent element (i.e. the button in this case) does not get triggered.

E.g.
```
<click-confirm>
  <button class="btn btn-sm btn-secondary" @click="eventHandler()">
    <i class="fa fa-eraser"></i>
  </button>
</click-confirm>
```

Looking at the code, a fix would just be a case of making the event being dispatched have a property of `bubbles` as true:

```
const mouseClick = new MouseEvent('click', {
  bubbles: true,
});
const cancelled = !this.target.dispatchEvent(mouseClick);
```

After examining the intercepted event, it also looks like `cancelable` and `composed` should also be true. Giving:

```
const mouseClick = new MouseEvent('click', {
  bubbles: true,
  cancelable: true,
  composed: true,
});
const cancelled = !this.target.dispatchEvent(mouseClick);
```

**Comment by GregPeden** [comment]
Thanks! I have affected your suggested fix.

https://github.com/SirLamer/click-confirm/releases/tag/v1.0.3
