### ISSUE TITLE
Official documentation placement or position 

### ISSUE THREAD

**Issue by JulienVerkest** [SirLamer/click-confirm#3]
On official documentation [https://sirlamer.github.io/click-confirm/](https://sirlamer.github.io/click-confirm/) there is a little mistake on the Placement examples, it's not position but placement property you should use.

**Comment by GregPeden** [comment]
Awesome thanks, I will fix it.

**Comment by GregPeden** [comment]
https://github.com/SirLamer/click-confirm/commit/84020b92706a051cadbf3deb6143ac50130bbd03
