### ISSUE TITLE
404 There isn't a GitHub Pages site here. sirlamer.github.io/click-confirm/

### ISSUE THREAD

**Issue by 4n70w4** [SirLamer/click-confirm#38]
![image](https://user-images.githubusercontent.com/38257723/150701003-108b0b55-40e3-4989-9b4c-cf0c0874c553.png)

**Comment by GregPeden** [comment]
You are right! It's because I changed my account name a few months ago. I'll fix this now.

**Comment by GregPeden** [comment]
BTW this is the correct URL: https://gregpeden.github.io/click-confirm/

**Comment by GregPeden** [comment]
Fixed: https://github.com/GregPeden/click-confirm/commit/c37b3ea6d7543a39f92fdcf395040adf75af19ff
