### ISSUE TITLE
click-confirm on async loop content

### ISSUE THREAD

**Issue by joaoprp** [SirLamer/click-confirm#5]
Hi,

I realized when I added <click-confirm> inside an async loop, the clicks weren't captured. I tried to add a button outside the loop and worked just fine so I believe it's either loop, async or a sum of both.

Can you put some light on it and help me on what should I do?

**Comment by GregPeden** [comment]
Umm... this might stress my skill a little, but could you share a code snippet which demonstrates the problem?

**Comment by joaoprp** [comment]
Sorry, never mind. The issue was with another plugin (to sort tables) that kidnaps click events. When I removed it, it worked fine.
