### ISSUE TITLE
Documentation broken

### ISSUE THREAD

**Issue by MorpheusXAUT** [SirLamer/click-confirm#8]
It appears like the documentation [linked](https://sirlamer.github.io/click-confirm/) in the README/top of the repo is currently broken - at least it only displays `<% if (htmlWebpackPlugin.options.description) { %> <% } %>` instead of the actual site content for me.
Looks like it's trying to load the stylesheet from `https://sirlamer.github.io/dev/style.css`, which returns a 404.
Current non-functional in Chrome 64.0.3282.119 and Firefox 58.0. I assume something changed with GitHub's page feature that rendered the documentation non-functional, since my regular package installation still works fine locally.

Just figured I'd point it out if other people are also running into this issue, looking for documentation 😄

**Comment by GregPeden** [comment]
Thank you, you are right, I will look in to that.

**Comment by GregPeden** [comment]
Fixed, I think GitHub changed the documentation location requirements and I didn't pick up on that, so it was loading the wrong index.html. I had to move assets around so that the documentation compiles to /docs
